junjeeong/Wikied

package-lock.json, package.json, src/api/article.ts, src/api/auth.ts, src/api/axios.ts, src/api/comment.ts, src/api/image.ts, src/api/notification.ts, src/api/profile.ts, src/api/user.ts
api에 있는 것들 ping 관련한 것 제외하고 일단 만들어보았는데 
쓰다가 오류나거나 추가 로직 필요한 부분들 있으면 수정하겠습니다~
=> Feat: api 함수 만들기

.gitignore, package-lock.json, postcss.config.js, src/styles/globals.css, tailwind.config.js
- globals.css 
- .gitignore
- package.json
- package-lock.json
- postcss.config.js
- tailwind.config.js
=> Feat: tailwind CSS 기본 설정파일 추가

src/components/SearchInput.tsx
- 기존의 코드에서 shadow-md placeholder:text-gray-400만 추가됨
=> Style: SearchInput 그림자 요소 추가해서 더 잘 보이도록 수정

src/components/ui/Modal/ConnectLostModal.tsx, src/components/ui/Modal/ModalOverlay.tsx, src/pages/login/index.tsx, src/store/AuthStore.tsx
위키 페이지에서 위키 참여하기 버튼을 누르고 5분 후에 띄워지는 모달 입니다.  
확인 버튼을 누르면 위키 페이지로 돌아갑니다.
=> Feat: 5분 modal  구현

src/components/Layout/Header.tsx
- 그냥 value prop 하나 없애준겁니다!
- 헤더에 profile이 안 보이는 버그는 LoginDropdown 컴포넌트의 문제였어요~
=> Fix: SearchInput에 value prop 삭제

next.config.mjs, src/components/Layout/Header.tsx, src/components/Logo.tsx, src/components/Navigation.tsx, src/components/UserMenu.tsx
- z-index, fixed 추가해서 상단 고정 시켰습니다
=> Reafactor: Header컴포넌트 상단고정, UI 컴포넌트 관심사 분리

src/hooks/useViewport.tsx
useViewport()
1. useViewport 임포트
2. const { width, isPC, isTablet, isMobile } = useViewport();
- 원하는 값만 가져다 사용
- width : number
- isPC,  isTablet, isMobile : boolean
=> Feat:useViewport 제작

src/components/SearchInput.tsx
=> Fix: SearchInput 입력했을 때 값이 남아있는 버그 개선, value prop 선택으로 변경

src/components/Layout/Header.tsx, src/hooks/useSearchName.tsx
=> Refactor: 커스텀훅으로 반응형, 폼 제출 로직 추상화

src/containers/QuizModalContainer.tsx
wiki page에서 code와 isMe를 받아서 사용
- 다른 사람 위키에 들어갔을 때  
- 내 위키에 들어갔을 때
=> Fix: Quiz-modal props 수정

package-lock.json, package.json, src/components/CustomToolbar.tsx, src/containers/AddBoardsEditor.tsx, src/pages/addboard/index.tsx, src/styles/global.css
=> Fix: 게시글 등록 페이지 제작 중

src/pages/api/signIn.ts
=> Fix: signIn.ts cookie 1.0.1에 호환되게 코드 변경

src/components/PaginationBar.tsx, src/containers/TotalArticlesContainer.tsx, src/pages/search/index.tsx
=> Fix: currentPage 기본값 지정

package-lock.json, package.json, src/containers/QuizModalContainer.tsx
=> Fix: Quiz modal input 값 초기화 및 input 값과 post ping 시간 전달

src/components/FormInput.tsx, src/containers/LoginFormContainer.tsx, src/containers/QuizSettingsFormContainer.tsx, src/containers/SignUpFormContainer.tsx, src/pages/login/index.tsx
=> Fix: login,signUp,QuizSetting 세로 정렬 및 form 제출 시 enter 이벤트 적용

src/containers/NotificationModalContainer.tsx
=> Fix: totalCount 예외처리

next.config.mjs, src/components/AlarmModal.tsx, src/components/NotifiCationModalOverlay.tsx, src/containers/NotificationModalContainer.tsx, src/containers/TotalArticlesContainer.tsx, src/pages/_app.tsx, src/pages/api/articles/index.ts, src/pages/api/notifications/index.ts, src/pages/api/signIn.ts
- next host 추가
- 알림모달 api수정
- 게시글 등록 api 수정
- login errorText 수정
=> Fix: next host 추가,알림모달 api수정,게시글 등록 api 수정

src/api/profile.ts, src/components/BestArticles.tsx, src/components/TotalArticles.tsx, src/containers/TotalArticlesContainer.tsx, src/pages/wiki/[name].tsx
=> Fix: patchProfile 수정

src/components/FormInput.tsx, src/components/QuizModal.tsx, src/pages/login/index.tsx
=> Fix: div -> form 엔터 적용

src/components/QuizModal.tsx
=> Fix: Quiz-modal form -> div

src/api/article.ts, src/api/handleError.ts, src/hooks/useFetchData.ts, src/utils/formatCurrentDate.ts
-getArticle 게시글 상세 조회 API가 로그인이 필요가 없어졌습니다.
=> chore: getArticle 게시글 상세 조회 api 함수 proxy->instance로 변경
